### ISSUE TITLE
想请问下为什么epub解析的每个章节监听鼠标事件的clientX数值特别大?

### ISSUE THREAD

**Issue by TJX666666** [yunser/epub-front#6]
在每一个章节的第一页是正常的,翻到后面页的话 他的clientX不会重置为0计数,而是一直叠加 可以到几千甚至上万  完全超过我屏幕的宽度 怎么解决啊??  感谢回答!

**Comment by TJX666666** [comment]
@cjhgit  您能给我解答一下吗 万分感谢!

**Comment by cjhgit** [comment]
哪个文件？哪行代码？ @TJX666666

**Comment by TJX666666** [comment]
> 哪个文件？哪行代码？ @TJX666666
在selection.js中您是这样引入的 :
`document.addEventListener('mouseup', function (e) {
    // console.log(e.clientX)
    var sel = window.getSelection()
    if (!sel.isCollapsed && true) selected(e) // TODO
    else window.parent.document.getElementById('select-menu').style.visibility = 'hidden'
})
`
我按照这种方式引入的话报错 :  Uncaught SyntaxError: Unexpected token '*'  selection.js:2

我之前使用的rendition.on('mouseup') 获取到的e.clientX 特别大  后来按照您的document.addEventListener clientX值正常  但是获取的只是document的 导致点击iframe这个区域的内容并不会触发 
感谢您的解答!
